In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
#qn1
arr1= np.empty((2,2))
#qn2
arr2= np.ones((4,2))
#qn3
arr3 = np.full((4,2),4)
#qn4
sample = np.array(([1,2],[3,4],[5,6],[7,8]))
arr4 = np.zeros_like(sample)
#qn5
arr5 = np.ones_like(sample)
#qn6
new_list = [1,2,3,4];
arr6 = np.array(new_list)
print(arr1,"\n",arr2,"\n",arr3,"\n",arr4,"\n",arr5,"\n",arr6)

[[3.42734890e-315 0.00000000e+000]
 [2.86530728e+161 8.43920881e-316]] 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[4 4]
 [4 4]
 [4 4]
 [4 4]] 
 [[0 0]
 [0 0]
 [0 0]
 [0 0]] 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]] 
 [1 2 3 4]


In [ ]:
import numpy as np
#q1
arr1 = np.arange(10,50)
#q2
sample=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2=np.reshape(sample,(1,9))
#qn3
sample2=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr3=np.eye(sample2.shape[0])
#qn4
sample4= np.random.random(30);
arr4= np.mean(sample4)
#qn5
sample5 = np.random.random((10,10))
arr5=np.max(sample5)
arr6=np.min(sample5)
#qn6
arr6 =np.zeros(10);
arr6[4]=1
#qn7
arr = [1,2,0,0,4,0]
arr7=np.flip(arr)
#qn8
arr8=np.ones((5,5),dtype=int)
arr8[1:-1,1:-1]=0
#qn9
arr9 = np.zeros((8,8),dtype=int)
arr9[1::2, ::2]=1
arr9[::2, 1::2]=1
print(arr9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np
#qn
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#qn1
sum = np.add(x,y)
#qn2
sub = np.subtract(x,y)
print(sub)
#qn3
mul = np.multiply(x,5)
print(mul)
#qn4
sq = np.square(x)
print(sq)
#qn5
dot= np.dot(v,w)
dot2 = np.dot(x,v)
dot3 = np.dot(x,y)
print(dot,"\n",dot2,"\n",dot3)
#qn6
con = np.concatenate((x,y),axis=1)
con2 = np.concatenate((v,w),axis=0)
print(con,"\n",con2)
#qn7
#con3 = np.concatenate((x,v),axis=0)
print("This gives an error because all the input arrays must have same number of dimensions")


[[-4 -4]
 [-4 -3]]
[[ 5 10]
 [15 25]]
[[ 1  4]
 [ 9 25]]
219 
 [29 77] 
 [[19 22]
 [50 58]]
[[1 2 5 6]
 [3 5 7 8]] 
 [ 9 10 11 12]
This gives an error because all the input arrays must have same number of dimensions


In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
#qn1
A_inv = np.linalg.inv(A)
print("A * A^-1 =\n", A @ A_inv)
#qn2
print("AB =\n", A @ B)
print("BA =\n", B @ A)
print("AB == BA?", np.array_equal(A @ B, B @ A))
#qn3
print("(AB)^T =\n", (A @ B).T)
print("B^T * A^T =\n", B.T @ A.T)
print("(AB)^T == B^T * A^T?", np.allclose((A @ B).T, B.T @ A.T))


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA? False
(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T? True


In [ ]:
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = A_inv @ B
print("Solution [x, y, z] =", X)


Solution [x, y, z] = [ 2.  1. -2.]


In [ ]:
import numpy as np
import time
#qn1
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("List addition time:", end - start, "seconds")
#qn2
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start, "seconds")
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("List multiplication time:", end - start, "seconds")
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start, "seconds")
#qn3
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("List dot product time:", end - start, "seconds")
start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start, "seconds")
#qn4
matrix_size = 1000
list_mat1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_mat2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
start = time.time()
result_list = [[sum(list_mat1[i][k] * list_mat2[k][j] for k in range(matrix_size))
                for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("List matrix multiplication time:", end - start, "seconds")
np_mat1 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
start = time.time()
result_np = np.matmul(np_mat1, np_mat2)
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")


List addition time: 0.07336091995239258 seconds
NumPy addition time: 0.0056073665618896484 seconds
List multiplication time: 0.07978320121765137 seconds
NumPy multiplication time: 0.0058019161224365234 seconds


TypeError: 'numpy.ndarray' object is not callable